spring.application.name=MyShoppingCartTask

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/shoppingcart
spring.datasource.username=postgres
spring.datasource.password=postres123

spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate/jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080


